### PR TITLE
Transition to Enketo Express; simplify Enketo configuration.

### PR DESCRIPTION
**Pull request by esmail**

### CODE REVIEW

**Comment by teodorescuserban** [comment]
@esmail please confirm ```ENKETO_API_ENDPOINT_PREVIEW='/webform/preview'``` this is not used anymore.

**Comment by esmail** [comment]
@teodorescuserban, I already responded when you asked in our [earlier conversation](https://www.flowdock.com/app/unocha/kobotoolbox/threads/D5SfyIQxpzdYuf1_8_ApBwv1vhs). Did that need further clarification?

**Comment by teodorescuserban** [comment]
Just wanted to keep the comments with the PR.
I am an old man, I'd forgot about it in like 2 weeks :)

On Wed, 20 Apr 2016, 18:07 Esmail, <notifications@github.com> wrote:

> @teodorescuserban <https://github.com/teodorescuserban>, I already
> responded when you asked in our earlier conversation
> <https://www.flowdock.com/app/unocha/kobotoolbox/threads/D5SfyIQxpzdYuf1_8_ApBwv1vhs>.
> Did that need further clarification?
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/UN-OCHA/kobo-stack-install/pull/1#issuecomment-212468134>
>
-- 
Serban Teodorescu
SysEngineer / DevOps

**Comment by esmail** [comment]
No worries, @teodorescuserban; Emma filled us in on some of the details of your new process.

**Pull request merged**
